# Generated by Django 4.1.3 on 2022-11-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_userfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user_id',
            field=models.ManyToManyField(blank=True, related_name='followers', to='insta.userfollowing'),
        ),
    ]
